// Octabam guide rewritten from the linked upstream docs at sambanks/octabam 666b615 on 2026-09-29.
// Keep remix and hardware claims tied to their individual upstream pages, and credit each
// hardware result to the image that ran, not to the remix name that now builds something newer.
const upstream = "https://github.com/sambanks/octabam/blob/main/";
const source = (label, path) => ({ label, url: upstream + path });

export const octabamPages = [
  {
    id: "overview", title: "Octabam", kicker: "Project map", summary: "A modular Octatrack firmware workbench with a full-machine emulator, virtual front panel, DSP effect lab, community ports, and guarded build tools.",
    sections: [
      { title: "The pieces fit together", paragraphs: ["Octabam builds a modified Octatrack OS from your own copy of OS 1.40C. A modification is a module (modules/<name>/); a named selection of modules is a remix (remixes/<name>/). make image REMIX=<name> composes a remix into a card-flashable image, refusing collisions by name and checking every ported module against its author's own build byte for byte. No firmware is distributed, and a built image must never be shared because it contains Elektron's OS.", "Around the build sit a ColdFire emulator that boots the image with both DSP cores, a browser front panel with sound, a DSP harness that renders effects to WAV files, and the interactive remixer. The presence of a module in the repository does not mean every combination has run on hardware: each module and remix page states its own proof."],
        table: { headers: ["Part", "Use it for", "Start here"], rows: [
          ["Build and flash", "Create a locally patched OS from stock 1.40C", "Build & flash"],
          ["Remixes", "See the four named remixes and what has run where", "Remix catalog"],
          ["Remixer", "Pick modules, inspect budgets, save and audition remixes", "Interactive remixer"],
          ["Emulator and panel", "Boot a remix with a project, controls, and sound", "Emulator & panel"],
          ["USB", "Add MIDI or multichannel audio over the Octatrack's USB port", "USB MIDI & audio"],
          ["DSP lab", "Render and compare effects without a device", "Effects & bus"],
          ["Tests", "Run build gates, DSP checks, and generated load projects", "Tests & limits"]
        ] } },
      { title: "Choose a first run", steps: [
        { title: "For software exploration", body: "You need macOS with the Xcode Command Line Tools and Homebrew (or Linux/WSL2, which is not yet verified end to end), Python 3.10+, cmake, and uv. Clone with submodules, set up, reconstruct your own stock OS, then launch the virtual panel. The panel stops without a project folder.", code: "git clone --recurse-submodules https://github.com/sambanks/octabam\ncd octabam\nmake setup\nmake emu-setup\nmake os && make recon\nmake emu-cf\nmake panel REMIX=ok-ms OT_PROJECT=/path/to/project" },
        { title: "For a hardware build", body: "Read Build & flash first, including recovery. Pick a remix from the catalog whose own page records a hardware run, run its checks, then build an image.", code: "make modules\nmake emu-cf\nmake check REMIX=ok-ms\nmake image REMIX=ok-ms BUILD=1" }
      ] },
      { title: "How to read status", paragraphs: ["Upstream marks proof per module and per remix: on hardware (with the unit and image), port-gated (passes its gates under the ColdFire emulator), local render (DSP harness only), or make check. A hardware result belongs to the image that ran. When a remix has changed since that image, the remix page says what has not been flashed in its current form; read it before assuming the current build is the tested one.", "Octabam's own effects have been tested only on an MKII. The DRAM platform has run on MKI units (octalab, 11 Sep 2026; octatrick-usb, 26 Sep 2026) and on midisc's author's unit (ok-ms, 14 Sep 2026)."] }
    ],
    sources: [source("Repository overview", "README.md"), source("Remix index", "docs/remixes/README.md"), source("Build guide", "docs/remixes/BUILDING.md"), source("Emulators", "docs/remixer/EMU.md")]
  },
  {
    id: "build", title: "Build & flash", kicker: "First hardware path", summary: "Prepare stock OS 1.40C, build a named remix, check it, and load the generated image from a CF card.",
    sections: [
      { title: "Prerequisites", paragraphs: ["You need an Octatrack MKI or MKII on OS 1.40C and its CF card; the stock 1.40C image is one file for both. The build host is macOS with the Xcode Command Line Tools (xcode-select --install) and Homebrew, plus Python 3.10+, cmake, and uv (brew install cmake uv). Keep a 5-pin DIN MIDI interface and a SysEx app (SysEx Librarian on macOS) for recovery; the Octatrack's own USB port does not take an OS upgrade.", "Native Windows is not supported; the build runs inside WSL2. BUILDING.md §1a gives the Ubuntu package list, but marks the Linux/WSL2 route as not verified since 9 Sep 2026: the build now needs the m68k-elf cross-toolchain, scripts/setup.sh installs it with Homebrew, and on a machine without Homebrew make setup stops at brew: command not found. Treat make setup, make image, and make check on Linux as unverified until someone reports a working run.", "Back up the card before loading a modified OS. Any remix that carries Octakit migrates Parts into Kits on project load, and going back to stock can lose Kit data."] },
      { title: "From clone to image", steps: [
        { title: "Get the repository and tools", body: "The recursive clone fetches the module authors' repositories (Octakit, MIDI SCENES, and timhastie/octatrick-modules) at pinned commits; if you cloned without it, run git submodule update --init. make setup installs binwalk, radare2, and m68k-elf-gcc with Homebrew and builds three pinned vendored tools; it ends with setup complete. make emu-setup puts the remixer and label-gate dependencies in .venv.", code: "git clone --recurse-submodules https://github.com/sambanks/octabam\ncd octabam\nmake setup\nmake emu-setup" },
        { title: "Get the stock OS", body: "make os downloads OCTATRACK_OS1.40C_dist.zip from Elektron into downloads/ and prints its SHA256 (expected 370c55a3dad3996b8e4b46400a205066fdaf185ad4d0255a3a3f835060573ff0). make recon unpacks it to out/raw/section_3_MAIN_OS.bin, which every build reads.", code: "make os\nmake recon" },
        { title: "Check the remix (optional, recommended)", body: "make emu-cf builds the ColdFire emulator; make check then builds the remix, runs every gate, and boots it under the emulator. Without make emu-setup the label gates skip, and without make emu-cf or a project in OT_PROJECT the set gates skip. It is slow: upstream measured 475 s for the shared half plus about 223 s per remix on one machine (27 Sep 2026), and about half an hour for bottleservice.", code: "make emu-cf\nmake check REMIX=ok-ms OT_PROJECT=/path/to/project" },
        { title: "Build the image", body: "This writes out/OCTATRACK_OCTABAM1.bin (the card image) and out/OCTATRACK_OS1.40C_OCTABAM1.syx (the MIDI image). BUILD is a one- or two-digit number that becomes the OS version string; bump it every time you flash. VERSION=<up to 10 chars> overrides the string.", code: "make image REMIX=ok-ms BUILD=1" }
      ] },
      { title: "CF-card upgrade and recovery", paragraphs: ["On the device, open PROJECT → SYSTEM → USB DISK MODE → YES. Copy out/OCTATRACK_OCTABAM1.bin to the card root, eject the card on the computer, leave USB disk mode, then choose PROJECT → SYSTEM → OS UPGRADE → YES. When it restarts, power-cycle once more before judging anything: an OS upgrade does not clear DSP RAM, and first boots have played garbled audio that a reboot cleared. SYSTEM STATUS → OS VERSION should read OCTABAM1.", "To return to stock: power off, hold FUNC and power on → STARTUP MENU → TRIG 3 → MIDI UPGRADE, then send downloads/extracted/OCTATRACK_OS1.40C.syx over DIN MIDI from your SysEx app. Do not power off during UPDATING FLASH. The Startup Menu lives in flash the OS upgrade never touches.", "After any remix that changes an effect's parameter layout (the bus rig family), stamp each project before playing it: python3 tools/hw/ot_project.py stamp-defaults <project dir> <remix>."], callout: "A build or emulator check cannot establish that a particular remix is safe for your projects. Read that remix's own page for what has run on a unit and in which image." }
    ],
    sources: [source("Build guide", "docs/remixes/BUILDING.md"), source("Linux and WSL2 notes", "docs/remixes/BUILDING.md#1a-linux-and-wsl2"), source("Flashing and recovery", "docs/remixer/FLASHING.md"), source("Failure modes", "docs/remixer/FAILURE_MODES.md")]
  },
  {
    id: "remixer", title: "Interactive remixer", kicker: "Compose a remix", summary: "Use the terminal interface to choose modules, inspect fit, save a configuration, and run checks or DSP auditioning.",
    sections: [
      { title: "Launch and orient", paragraphs: ["make remix is a Textual terminal app; it needs the .venv from make emu-setup and a built image for its emulator view. It has three panes: Available (every module and stock effect that could be in an image), Choosers (the FX1 and FX2 menus in panel row order), and the unit pane (the highlighted effect's knobs and the ledger lines it is party to). Nothing in it touches hardware.", "Playback uses afplay, so it only plays on macOS as shipped. On Linux or WSL2 the r key still renders; REMIXER.md gives a small afplay wrapper around paplay for WSLg's PulseAudio."], code: "make emu-setup\nmake bus REMIX=ok-ms\nmake remix" },
      { title: "Common controls", table: { headers: ["Key", "Action"], rows: [["Enter", "Available: add the module; Choosers: remove the row"], ["1", "Give the highlighted effect an FX1 row, or take it off"], ["f / x", "Pick the fallback / apply the fix a warning line names"], ["l / s / k", "Load a remix (or stock), save the selection as one, reset to stock"], ["c", "Run make check"], ["r / space / esc", "Render the effect under the cursor and play it / replay / stop"], ["a / b / , / .", "Mark A / render and mark B / play A / play B"], ["d", "Choose the sample folder"], ["? / q", "Help / quit"]] }, paragraphs: ["The interface reports collisions and budget use, and names the bridge module that would clear a collision. Saving writes remixes/<name>/remix.py and a README stub; it does not flash anything."] },
      { title: "Modules, choosers, and placement", paragraphs: ["A module's manifest declares what it is (knobs, hooks, resource claims, payloads), not an address. The build places its code in one of three places: a ROM cave in the OS image's free runs (about 8 KB shared by everyone), a DRAM unit linked into one runtime and unpacked at boot into a 10 MB reserve carved from the 85.5 MB sample/recorder pool, or an appended runtime such as Octakit's. Two modules that claim one address, hook, id, or buffer are refused by name; some pairs need a bridge module, as Octakit and MIDI SCENES need KITS RELOAD in ok-ms.", "make modules prints every module, the pairwise compatibility matrix, and every remix. A remix you write by hand also needs a README.md and a re-rendered index (make docs), or make check refuses it."], code: "make modules\nmake docs\nmake check REMIX=<name>" }
    ],
    sources: [source("Remixer controls", "docs/remixer/REMIXER.md"), source("Module guide", "docs/remixer/MODULES.md"), source("Placement and budgets", "docs/remixer/PLACEMENT.md"), source("Your own remix", "docs/remixes/BUILDING.md#8-your-own-remix")]
  },
  {
    id: "remixes", title: "Remix catalog", kicker: "Known combinations", summary: "The four named remixes, the one-module test remixes, and what each has actually run on.",
    sections: [
      { title: "Pick by evidence", paragraphs: ["A remix is a build recipe, not a downloadable firmware file. Build it from your own stock OS with make image REMIX=<name> BUILD=<number>. Upstream removed about ten earlier remixes on 27–28 Sep 2026 (among them bamsep26, recfix, usb-lean, and hello); the four below are the named remixes, and everything else is a test remix that carries one module for its gates.", "The status column follows each remix's own README, which is more specific than the generated index. Upstream changes quickly, so check both again before flashing."],
        table: { headers: ["Remix", "What it combines", "What has run (as of 29 Sep 2026)"], rows: [
          ["bottleservice", "The bus rig (delay and reverb bus, three FX1 stations), scene locks on page 2, TEMPO window for the bus, USB MIDI, USB AUDIO OUT MASTER, USB AUDIO IN CD, and Octakit", "Image 88 ran on Sam's MKII (27 Sep); which features were tried there is not written down. Not flashed in its current form: OUT MASTER now polls every 250 µs (image 88 polled every 1 ms), and USB AUDIO IN CD with USB CROSSBAR has not run on a unit. Trigs on track 1 beside the delay pop and click (29 Sep, cause open)."],
          ["ok-ms", "Octakit + MIDI SCENES + KITS RELOAD bridge on the stock effects", "midisc's author's unit, 14 Sep (OKMS1, then OKMS2 with the bridge)"],
          ["octatrick-usb", "SYNTH MACHINE, SCALE QUANTIZER, DIRECT JUMP, USB MIDI, and 20-channel USB audio on the stock effects", "Tim's MKI as OCTATRICK9, 26 Sep; images built from the repo are byte-identical to the one he flashed"],
          ["octatrick", "The same three modules without USB", "make check only (emulator-verified)"],
          ["repitch (test)", "REPITCH on the stock effects", "repeat98's MKII, 16 Sep (OCTABAM81)"],
          ["tapeecho (test)", "Tape Echo in place of Spring Reverb", "The author's unit (OCTACLID4): six instances run, a seventh freezes it (open)"],
          ["usb-audio (test)", "The rig without Octakit or scenes, plus USB MIDI and USB audio", "Sam's MKII as images 64 (16 channels, 16-bit) and 69 (16 channels, 24-bit), 25 Sep; see the USB page for the 20-channel stream"],
          ["bus (test)", "BusVerb + BusDelay + SEND + TEMPO SYNC, the bit-identity fixture", "Upstream: on hardware under earlier names; not a remix to flash"],
          ["mods (test)", "Every ColdFire mod that fits in one image: Octakit, MIDI SCENES, the recorder fixes, REPITCH, CC MAP, USB", "Port-gated"],
          ["usb, usb-out-*, usb-io-* (test)", "One USB configuration each", "Port-gated or make check; see the USB page for the images that ran"],
          ["octakit, midi-scenes, lofi-amf-fix (test)", "One module alone", "make check; Octakit and MIDI SCENES ran inside ok-ms"],
          ["euclid, miniverb (test)", "One effect alone", "Local render only"],
          ["cfmeter, cfmeter-port (test)", "Timing probes", "Port-gated; the numbers need a unit"]
        ] } },
      { title: "Two useful starting points", steps: [
        { title: "Octakit with MIDI SCENES", body: "ok-ms pairs the two ports through a bridge and keeps stock effects, so existing projects play as they did. Octakit migrates Parts to Kits on project load; back up the card first.", code: "make check REMIX=ok-ms OT_PROJECT=/path/to/project\nmake image REMIX=ok-ms BUILD=1" },
        { title: "The bus rig", body: "bottleservice hosts the delay on T1 FX2 and the reverb on T5 FX2, with SEND on the other tracks. A new project is born wired that way; a project made before this remix needs the host and stamp-defaults commands before you open it. Read its Where it has run section first.", code: "make image REMIX=bottleservice BUILD=91\npython3 tools/hw/ot_project.py host \"<card>/<set>/<project>\"\npython3 tools/hw/ot_project.py stamp-defaults \"<card>/<set>/<project>\" bottleservice" }
      ] }
    ],
    sources: [source("Remix index", "docs/remixes/README.md"), source("bottleservice", "remixes/bottleservice/README.md"), source("ok-ms", "remixes/ok-ms/README.md"), source("octatrick and octatrick-usb", "remixes/octatrick/README.md"), source("usb and usb-audio", "remixes/test/usb/README.md")]
  },
  {
    id: "emulator", title: "Emulator & panel", kicker: "Run the machine", summary: "Boot a patched Octatrack locally, operate a virtual panel, and test a project before using hardware.",
    sections: [
      { title: "Two emulation layers", paragraphs: ["The port (tools/emu/ot_emu, C++) runs the ColdFire firmware with both DSP56300 cores, the card, the panel link, MIDI, and USB. make check's boot verifier, the set gates, make panel, and make emu-live all run on it. Tier-0 (tools/emu/emu_bringup.py, on Unicorn) boots to the RTOS handoff and calls the firmware's draw and formatter code directly; the label gates and the remixer's unit pane use it. The older Route A backend was retired on 26 Sep 2026; parts of the panel README below its In octabam section still describe it.", "Neither layer sees caches, the recorder's DMA, or all cross-core timing. A passing check means the tested path ran in the emulator; hardware evidence is recorded separately on each remix page."] },
      { title: "Open the browser panel", steps: [
        { title: "Prepare emulator tools and firmware", body: "Complete the setup and stock-OS steps from Build & flash. make emu-setup supplies the panel's audio dependencies and make emu-cf builds the port.", code: "make emu-setup\nmake emu-cf" },
        { title: "Launch with a remix and a project", body: "make panel needs a project: OT_PROJECT=<dir>, or a path in ~/.octabam_project; without either it stops. It builds the remix, copies it to out/panel_<remix>.bin, and serves the panel at http://localhost:8563/ with the LCD, keys, encoders, crossfader, LEDs, and sound.", code: "make panel REMIX=ok-ms OT_PROJECT=/path/to/your/project" },
        { title: "The virtual card persists", body: "The card is out/cards/<project folder name>.img. The first run creates it from the project and its sibling AUDIO folder; later runs boot the file as it is, with write-back, so what you save stays. Delete that image to regenerate it from the folder, or pass PANEL_CARD= for another." }
      ] },
      { title: "Other panel modes", paragraphs: ["make emu-live opens the screen and keys in a Tk window with no sound, on a scratch card, taking the project the same way. The browser panel can use another port or boot without the DSP cores, and make panel-app builds a macOS app (out/Virtual Panel.app). The panel runs the port as an MKII by default; PANELARGS=--mki runs it as an MKI."], code: "make emu-live REMIX=ok-ms OT_PROJECT=/path/to/project\nmake panel REMIX=ok-ms OT_PROJECT=/path/to/project PANEL_PORT=8571 PANELARGS='--sound off'\nmake panel-app" }
    ],
    sources: [source("Emulator guide", "docs/remixer/EMU.md"), source("Virtual panel", "tools/panel/README.md"), source("How the testing works", "docs/remixer/TESTING.md")]
  },
  {
    id: "usb", title: "USB MIDI & audio", kicker: "Computer connection", summary: "Choose a USB build, understand its channel map, and tell the images that ran on hardware from the configurations that only pass under the emulator.",
    sections: [
      { title: "Which USB build?", paragraphs: ["USB MIDI and the USB audio output modules come from markandrus/octemu; the USB audio input modules and USB CROSSBAR come from bryantysinger. All run on Octabam's DRAM platform. USB audio is one source assembled several ways, one module each, and each has a one-module test remix. Two named remixes carry USB: octatrick-usb (stock effects plus the 20-channel stream, run on an MKI) and bottleservice (the rig, with track 8 out and a stereo pair in)."],
        table: { headers: ["Build", "USB functions", "What has run"], rows: [
          ["octatrick-usb", "USB MIDI + 20-channel out (tracks, MAIN, CUE)", "Tim's MKI, OCTATRICK9, 26 Sep: all 20 channels"],
          ["usb-audio (test)", "The rig + USB MIDI + 20-channel out", "Sam's MKII: images 64 and 69 (16 channels), 25 Sep"],
          ["usb-out-tracks-main-cue (test)", "Stock effects + USB MIDI + 20-channel out", "Bryan's MKII, image 90 (20 channels), 25 Sep; the index lists the remix as port-gated"],
          ["bottleservice", "USB MIDI + OUT MASTER (track 8) + IN CD", "Image 88 on Sam's MKII polled OUT MASTER every 1 ms; the current 250 µs build and IN CD are not flashed"],
          ["usb (test)", "USB MIDI only, with the rig", "Not flashed alone; its module ran inside image 64"],
          ["usb-io-* and other usb-out-* (test)", "Other in/out combinations", "Port-gated, 28 Sep; not on hardware in these forms"]
        ] } },
      { title: "Audio routing", paragraphs: ["In the 20-channel stream at USB high speed, track N's post-FX, pre-fader stereo pair is on channels 2N−1 and 2N (T1 on 1–2 through T8 on 15–16), MAIN on 17–18, and CUE on 19–20. At full speed the stream is the stereo sum of the tracks. Track LEVEL, the crossfader, MAIN volume, and the master effects are not in the track channels.", "USB AUDIO IN modules put a stereo pair (AB or CD) or four channels (ABCD) from the computer onto the inputs; the jacks are used while the stream is closed. The four-channel form ran on Bryan T's MKII as usbin-test build 16 (27 Sep 2026); the modules as packaged are port-gated.", "USB MIDI takes incoming messages through the DIN input path and sends everything the unit sends on DIN over USB too. OS upgrades still need the CF card or 5-pin DIN MIDI."] },
      { title: "Build and connect", steps: [
        { title: "Prepare and check", body: "Complete the stock OS and toolchain steps in Build & flash. In make check, verify_usb enumerates the image under the emulator and streams from it; that is separate from hardware testing.", code: "make emu-cf\nmake check REMIX=octatrick-usb\nmake image REMIX=octatrick-usb BUILD=1" },
        { title: "Load the image and power-cycle", body: "Back up the card and use the CF upgrade path in Build & flash. Power the unit fully off after the upgrade: on OCTATRICK9, MAIN and CUE were silent until a full power-off. For a rig remix and an old project, run the host and stamp-defaults commands from the Remix catalog first." },
        { title: "Record on macOS", body: "Audio MIDI Setup lists Elektron Octatrack DPS-1 with a 20-channel 44.1 kHz input and a MIDI port. Select it as the input in your DAW, or record 60 s of all twenty channels with SoX.", code: "sox -t coreaudio \"Elektron Octatrack DPS-1\" -c 20 -r 44100 -b 24 take.wav trim 0 60" }
      ] },
      { title: "What has been measured", paragraphs: ["Image 64 on Sam's MKII (25 Sep) enumerated on macOS with a 16-channel input: every channel carried its track, 9.6 minutes recorded with no discontinuities after the first 1.6 s of each stream, zero underruns and overruns, and USB MIDI input took 7,950 messages/s for 185 s without a stall. Image 69 did the same at 24 bits. Image 90 on Bryan's MKII carried MAIN and CUE on channels 17–20. OCTATRICK9 on Tim's MKI streamed all 20 channels, the first MKI run of the stream.", "Still open: a burst of reordered samples 0.75–1.5 s after the host opens a stream, on four of five takes. Not measured: USB MIDI transmit from the unit, USB MIDI timing against DIN, disk mode entered with a session open, and Windows or Linux hosts."] }
    ],
    sources: [source("usb and usb-audio", "remixes/test/usb/README.md"), source("20-channel output module", "modules/usb-audio-out-tracks-main-cue/README.md"), source("USB MIDI module", "modules/usb-midi/README.md"), source("USB input (ABCD)", "modules/usb-audio-in-abcd/README.md"), source("octatrick-usb", "remixes/octatrick/README.md"), source("Hardware failure notes", "docs/remixer/FAILURE_MODES.md")]
  },
  {
    id: "effects", title: "Effects & bus", kicker: "DSP workbench", summary: "Understand the shared send bus, the rig in bottleservice, and the audio renderer used to audition effects.",
    sections: [
      { title: "The shared bus", paragraphs: ["Octabam's XBUS is one aux bus shared by every track. BusDelay is hosted on T1 FX2 and BusVerb on T5 FX2; the other tracks run SEND, whose DEL and REV knobs set how much goes to each. The delay's repeats also feed the reverb through the reverb's DLY knob (DLY 0 runs the two engines in parallel). Each engine's wet signal comes out on the track that hosts it: T1 carries the repeats, T5 the tail.", "In bottleservice, T8 keeps the stock DELAY, and three FX1 stations replace stock FILTER, LO-FI, and CHORUS: SPECTRUM (filters), CHARACTER (drive, fold, compressor), and MODULATION (Juno, Dimension, flanger, comb, phaser). New projects are born hosted this way; older projects keep their stored effect ids until you run the host command. Tracks 1 and 5 have been tested as THRU tracks without trigs of their own; sounds programmed on track 1 beside the delay pop and click (reported 29 Sep 2026, cause open)."] },
      { title: "Audition outside the full emulator", paragraphs: ["The DSP harness runs the assembled DSP56300 instructions against WAV or tone input. It is useful for effect development, regression comparisons, and A/B listening. It does not model the whole Octatrack or prove hardware timing. The render targets need a remix that carries both bus servers: bus (the test fixture) or bottleservice. render-rig writes one WAV per track plus the mixed output."], code: "make reverb IN=loop.wav ARGS='--wet --mode all'\nmake render REMIX=bus\nmake render-delay REMIX=bus\nmake render-rig REMIX=bus" },
      { title: "Effect modules", table: { headers: ["Module", "Role", "Start with"], rows: [["BusVerb", "Shared reverb engine (ROOM, PLATE, BIG, shimmer, gate)", "modules/busverb/README.md"], ["BusDelay", "Shared delay engine (CLEAN, GRAIN, REVERSE, tape wow)", "modules/busdelay/README.md"], ["SEND", "Bus client on every other track", "modules/send/README.md"], ["XBUS", "Send and return architecture", "docs/effects/XBUS.md"], ["bottleservice", "The rig as it ships, with its track and knob map", "remixes/bottleservice/README.md"]] }, paragraphs: ["These are repository paths, so you can read the exact controls and current limitations. Octabam's own effects have been tested only on an MKII. Run make modules for the full effect inventory; it changes faster than this guide."] }
    ],
    sources: [source("Bus architecture", "docs/effects/XBUS.md"), source("The rig", "remixes/bottleservice/README.md"), source("DSP harness", "docs/remixer/HARNESS.md"), source("BusVerb module", "modules/busverb/README.md"), source("BusDelay module", "modules/busdelay/README.md")]
  },
  {
    id: "modules", title: "Modules & ports", kicker: "Extend the OS", summary: "Find integrated community work and learn the shape of a module before writing or combining one.",
    sections: [
      { title: "What is integrated", paragraphs: ["Octabam includes its own modules and community work, some of it pulled in as submodules from the authors' repositories. make modules gives the exact inventory and the compatibility matrix. A port means the code builds in the remixer and matches its author's build; hardware evidence belongs to the specific image that carried it."],
        table: { headers: ["Area", "What it adds", "Carried by"], rows: [["Octakit (emuyia)", "256 named Kits per project in place of 64 Parts; migrates old projects", "ok-ms, bottleservice, mods"], ["MIDI SCENES (bkkbrls-del)", "Scene locks driven over MIDI", "ok-ms, mods"], ["Octatrick (timhastie)", "FM synth machine, scale quantizer with glide, direct pattern jump", "octatrick, octatrick-usb"], ["USB (markandrus, bryantysinger)", "USB MIDI, USB audio out and in", "octatrick-usb, bottleservice, USB test remixes"], ["REPITCH (repeat98)", "Tempo-following playback by speed", "repitch, mods"], ["Recorder fixes (sambanks)", "RECORDER SPACING, FLEX SEEK BIND, FLEX SEEK BIND CTR (on hardware, OCTABAM83, 12 Sep); RECORDER HOLD and RLEN PLEN (port-gated)", "mods"], ["LOFI AMF FIX (bryantysinger)", "Fixes stock LO-FI's AMF knob", "lofi-amf-fix, mods"], ["Bridges", "KITS RELOAD, SCENES KITS, SCENES P2 KITS: glue between larger ports", "ok-ms, bottleservice, mods"]] } },
      { title: "Make a small module", paragraphs: ["Each module has a manifest.py describing its name, knobs, hooks, resource claims, and payloads. For a DSP effect, copy modules/_template/ and follow modules/character/, an in-place insert with its own render gate. For a ColdFire change (parts, kits, menus, MIDI, fixes), copy modules/_template_cf/ and follow modules/repitch/. CONTRIBUTING.md is the contract a pull request signs; issues are disabled upstream, and pull requests are accepted."], code: "make check REMIX=bottleservice\npython3 tools/remix/audition.py character out/dry/drums_110.wav DRV=64\npython3 tools/verify/verify_character.py" },
      { title: "Understand the fit", paragraphs: ["The ROM caves total about 8 KB shared by every module, so larger features use a DRAM unit in the 10 MB reserve taken from the sample pool. Bridges resolve behavioral interactions that placement alone cannot fix. The same module can have different results in different remixes: the mods remix, for example, cannot carry the three Octatrick modules because they collide with Octakit's recipe and the free ROM.", "Before publishing a combination, record exactly which remix and image were checked and what was observed on hardware."] }
    ],
    sources: [source("Module guide", "docs/remixer/MODULES.md"), source("Contributing", "CONTRIBUTING.md"), source("Memory placement", "docs/remixer/PLACEMENT.md"), source("mods remix", "remixes/test/mods/README.md"), source("Module template", "modules/_template/README.md")]
  },
  {
    id: "testing", title: "Tests & limits", kicker: "Evidence before flashing", summary: "Use the build gates, emulator, audio renderer, and generated stress project for the questions each can answer.",
    sections: [
      { title: "A sensible check sequence", steps: [
        { title: "Check composition", body: "make modules shows inventory and compatibility. make check is two halves: the shared gates (ledger selftest, the audit that builds every remix, docs, knob census, module gates) and the selected remix's build, cycle count, and own gates. Prepare both emulators and pass a project so fewer gates skip. make reach lists the gates a branch's changes reach, and RUN=1 runs them.", code: "make modules\nmake emu-setup && make emu-cf\nmake check REMIX=ok-ms OT_PROJECT=/path/to/project\nmake reach" },
        { title: "Listen and interact", body: "Use the DSP renderer to compare effect output, then boot the selected remix in the browser panel with a copied project. Exercise the controls and patterns relevant to that remix.", code: "make render-rig REMIX=bus\nmake panel REMIX=ok-ms OT_PROJECT=/path/to/your/project" },
        { title: "Run a dense project", body: "The stress-project generator writes out/stress-project with eight FLEX tracks, three active LFOs per track, and bank A patterns of increasing trig density, placed from the chosen remix's modules at their most expensive settings. It refuses to overwrite an existing output; --source picks another saved project and --out another destination. STRESS_PROJECT.md explains how to run it in the emulator and on hardware.", code: "python3 tools/harness/stress_project.py --remix bottleservice" }
      ] },
      { title: "What the result means", table: { headers: ["Check", "Good evidence for", "Does not establish"], rows: [["Build and static gates", "Module fit, collisions, byte-for-byte match with the author's build", "Real device behavior"], ["DSP harness", "Effect instructions and audio output", "Full device scheduling"], ["ColdFire port", "Boot, menus, a real project, short playback, USB enumeration", "Caches, recorder DMA, or all cross-core timing"], ["Hardware trial", "That image on that device and project", "Every combination, a later build, or a long-run workload"]] }, paragraphs: ["CI (make ci) runs only the checks that need no firmware. TESTING.md lists what each gate proves and which gates are blind to what. FAILURE_MODES.md records what has gone wrong on real units. Use both, plus the remix's own page, when deciding whether a build is ready for your machine."] }
    ],
    sources: [source("How the testing works", "docs/remixer/TESTING.md"), source("Stress-project generator", "tools/harness/STRESS_PROJECT.md"), source("Emulator limitations", "docs/remixer/EMU.md"), source("Failure modes", "docs/remixer/FAILURE_MODES.md"), source("Remix index", "docs/remixes/README.md")]
  }
];
